spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5435/booking_db
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info