ALTER TABLE users
ALTER
COLUMN full_name TYPE VARCHAR(255) USING (full_name::VARCHAR(255));

ALTER TABLE users
ALTER
COLUMN phone TYPE VARCHAR(255) USING (phone::VARCHAR(255));

ALTER TABLE users
ALTER
COLUMN preferred_language TYPE VARCHAR(255) USING (preferred_language::VARCHAR(255));

ALTER TABLE users
ALTER
COLUMN role TYPE VARCHAR(255) USING (role::VARCHAR(255));

ALTER TABLE users
    ALTER COLUMN updated_at SET NOT NULL;